#!/bin/sh

$PATH_TO_HATENO_JOBS $JOBS_STATES_FILENAME set $JOB_ID running

{
	### BEGIN_COMMAND_LINES ###
	$ITEM_VALUE &&
	### END_COMMAND_LINES ###
	$PATH_TO_HATENO_JOBS $JOBS_STATES_FILENAME set $JOB_ID succeed
} || {
	$PATH_TO_HATENO_JOBS $JOBS_STATES_FILENAME set $JOB_ID failed
}
